
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Qui NON si usa env("DATABASE_URL"): l'helper di Prisma solleva un errore appena il file
    // viene caricato se la variabile manca, e questo file viene caricato anche da
    // `prisma generate`, che gira nel postinstall e di un URL non ha alcun bisogno. Sulla
    // macchina di build (dove esistono solo le variabili TURSO_*) quell'errore faceva fallire
    // l'intero `npm install`, e quindi il deploy.
    //
    // Il valore serve davvero solo ai comandi `prisma migrate`/`db`, che si lanciano in locale
    // con .env caricato: il ripiego qui sotto è il database di sviluppo.
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
